apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: webapps
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
